---
kind: pipeline
name: test-on-amd64

platform:
  arch: amd64

steps:
- name: test
  image: python:3.6
  commands:
  - pip install -r requirements.txt

---
kind: pipeline
name: test-on-arm64

platform:
  arch: arm64

steps:
- name: test
  image: python:3.6
  commands:
  - pip install -r requirements.txt