local Pipeline(name, image, arch) = {
  kind: "pipeline",
  platform:
    arch: arch
  name: name,
  steps: [
    {
      name: "test",
      image: image,
      commands: [
        "pip install -r requirements.txt",
        "pytest"
      ]
    }
  ]
};

[
  Pipeline("python-3-6-arm64", "python:3.6", "arm64"),
  Pipeline("python-3-7-arm64", "python:3.7", "arm64"),
  Pipeline("python-3-8-arm64", "python:3.8", "arm64"),
]