---
kind: pipeline
type: kubernetes
name: python-3-6
platform:
  os: linux
  arch: arm64

steps:
- name: test
  image: python:3.6
  commands:
  - pip install -r requirements.txt

---
kind: pipeline
type: kubernetes
name: python-3-7
platform:
  os: linux
  arch: arm64

steps:
- name: test
  image: python:3.7
  commands:
  - pip install -r requirements.txt
