matrix:
  PYTHON_VERSION:
    - 3.6
    - 3.7
    - 3.8

pipeline:
  test:
    platform:
      os: linux
      arch: arm64
    image: python:${PYTHON_VERSION}
    commands:
      - pip install -r requirements.txt