---
kind: pipeline
name: py36-on-arm64

platform:
  arch: arm64

steps:
- name: build
  image: python:3.6
  commands:
  - apt-get update
  - apt-get -y install autogen autoconf automake libtool pkg-config libjson-c-dev gettext libusb-1.0-0-dev
  - apt-get -y install libdbus-glib-1-dev libbluetooth-dev libnl-genl-3-dev flex bison libpcap-dev
  - git clone --branch libgpg-error-1.39 https://github.com/gpg/libgpg-error
  - cd libgpg-error
  - ./autogen.sh
  - ./configure -enable-maintainer-mode --enable-static --enable-shared --with-pic --disable-doc --disable-nls
  - make
  - make install
  - cd ..
  - rm -rf libgpg-error
  - git clone --branch libgcrypt-1.8.6 https://github.com/gpg/libgcrypt
  - cd libgcrypt
  - ./autogen.sh
  - ./configure -enable-maintainer-mode --enable-static --enable-shared --with-pic --disable-doc
  - make
  - make install
  - cd ..
  - rm -rf libgcrypt
  - git clone --branch fanout https://github.com/tsnoam/libpcap
  - cd libpcap
  - ./configure --enable-ipv6 --disable-universal --enable-dbus=no --without-libnl
  - make
  - make install
  - cd ..
  - rm -rf libpcap
  - git clone --branch dev https://github.com/ntop/nDPI.git
  - cd nDPI
  - ./autogen.sh
  - ./configure
  - make
  - make install
  - cd ..
  - rm -rf nDPI
  - pip install wheel twine setuptools codecov
  - pip install -r requirements.txt
  - python setup.py bdist_wheel
  - ls dist/

---
kind: pipeline
name: py37-on-arm64

platform:
  arch: arm64

steps:
- name: build
  image: python:3.7
  commands:
  - apt-get update
  - apt-get -y install autogen autoconf automake libtool pkg-config libjson-c-dev gettext libusb-1.0-0-dev
  - apt-get -y install libdbus-glib-1-dev libbluetooth-dev libnl-genl-3-dev flex bison libpcap-dev
  - git clone --branch libgpg-error-1.39 https://github.com/gpg/libgpg-error
  - cd libgpg-error
  - ./autogen.sh
  - ./configure -enable-maintainer-mode --enable-static --enable-shared --with-pic --disable-doc --disable-nls
  - make
  - make install
  - cd ..
  - rm -rf libgpg-error
  - git clone --branch libgcrypt-1.8.6 https://github.com/gpg/libgcrypt
  - cd libgcrypt
  - ./autogen.sh
  - ./configure -enable-maintainer-mode --enable-static --enable-shared --with-pic --disable-doc
  - make
  - make install
  - cd ..
  - rm -rf libgcrypt
  - git clone --branch fanout https://github.com/tsnoam/libpcap
  - cd libpcap
  - ./configure --enable-ipv6 --disable-universal --enable-dbus=no --without-libnl
  - make
  - make install
  - cd ..
  - rm -rf libpcap
  - git clone --branch dev https://github.com/ntop/nDPI.git
  - cd nDPI
  - ./autogen.sh
  - ./configure
  - make
  - make install
  - cd ..
  - rm -rf nDPI
  - pip install wheel twine setuptools codecov
  - pip install -r requirements.txt
  - python setup.py bdist_wheel
  - ls dist/

---
kind: pipeline
name: py38-on-arm64

platform:
  arch: arm64

steps:
- name: build
  image: python:3.8
  commands:
  - apt-get update
  - apt-get -y install autogen autoconf automake libtool pkg-config libjson-c-dev gettext libusb-1.0-0-dev
  - apt-get -y install libdbus-glib-1-dev libbluetooth-dev libnl-genl-3-dev flex bison libpcap-dev
  - git clone --branch libgpg-error-1.39 https://github.com/gpg/libgpg-error
  - cd libgpg-error
  - ./autogen.sh
  - ./configure -enable-maintainer-mode --enable-static --enable-shared --with-pic --disable-doc --disable-nls
  - make
  - make install
  - cd ..
  - rm -rf libgpg-error
  - git clone --branch libgcrypt-1.8.6 https://github.com/gpg/libgcrypt
  - cd libgcrypt
  - ./autogen.sh
  - ./configure -enable-maintainer-mode --enable-static --enable-shared --with-pic --disable-doc
  - make
  - make install
  - cd ..
  - rm -rf libgcrypt
  - git clone --branch fanout https://github.com/tsnoam/libpcap
  - cd libpcap
  - ./configure --enable-ipv6 --disable-universal --enable-dbus=no --without-libnl
  - make
  - make install
  - cd ..
  - rm -rf libpcap
  - git clone --branch dev https://github.com/ntop/nDPI.git
  - cd nDPI
  - ./autogen.sh
  - ./configure
  - make
  - make install
  - cd ..
  - rm -rf nDPI
  - pip install wheel twine setuptools codecov
  - pip install -r requirements.txt
  - python setup.py bdist_wheel
  - ls dist/

---
kind: pipeline
name: py39-on-arm64

platform:
  arch: arm64

steps:
- name: build
  image: python:3.9
  commands:
  - apt-get update
  - apt-get -y install autogen autoconf automake libtool pkg-config libjson-c-dev gettext libusb-1.0-0-dev
  - apt-get -y install libdbus-glib-1-dev libbluetooth-dev libnl-genl-3-dev flex bison libpcap-dev
  - git clone --branch libgpg-error-1.39 https://github.com/gpg/libgpg-error
  - cd libgpg-error
  - ./autogen.sh
  - ./configure -enable-maintainer-mode --enable-static --enable-shared --with-pic --disable-doc --disable-nls
  - make
  - make install
  - cd ..
  - rm -rf libgpg-error
  - git clone --branch libgcrypt-1.8.6 https://github.com/gpg/libgcrypt
  - cd libgcrypt
  - ./autogen.sh
  - ./configure -enable-maintainer-mode --enable-static --enable-shared --with-pic --disable-doc
  - make
  - make install
  - cd ..
  - rm -rf libgcrypt
  - git clone --branch fanout https://github.com/tsnoam/libpcap
  - cd libpcap
  - ./configure --enable-ipv6 --disable-universal --enable-dbus=no --without-libnl
  - make
  - make install
  - cd ..
  - rm -rf libpcap
  - git clone --branch dev https://github.com/ntop/nDPI.git
  - cd nDPI
  - ./autogen.sh
  - ./configure
  - make
  - make install
  - cd ..
  - rm -rf nDPI
  - pip install wheel twine setuptools codecov
  - pip install -r requirements.txt
  - python setup.py bdist_wheel
  - ls dist/

---
kind: pipeline
name: py36-on-arm32

platform:
  arch: arm

steps:
- name: build
  image: python:3.6
  commands:
  - apt-get update
  - apt-get -y install autogen autoconf automake libtool pkg-config libjson-c-dev gettext libusb-1.0-0-dev
  - apt-get -y install libdbus-glib-1-dev libbluetooth-dev libnl-genl-3-dev flex bison libpcap-dev
  - git clone --branch libgpg-error-1.39 https://github.com/gpg/libgpg-error
  - cd libgpg-error
  - ./autogen.sh
  - ./configure -enable-maintainer-mode --enable-static --enable-shared --with-pic --disable-doc --disable-nls
  - make
  - make install
  - cd ..
  - rm -rf libgpg-error
  - git clone --branch libgcrypt-1.8.6 https://github.com/gpg/libgcrypt
  - cd libgcrypt
  - ./autogen.sh
  - ./configure -enable-maintainer-mode --enable-static --enable-shared --with-pic --disable-doc
  - make
  - make install
  - cd ..
  - rm -rf libgcrypt
  - git clone --branch fanout https://github.com/tsnoam/libpcap
  - cd libpcap
  - ./configure --enable-ipv6 --disable-universal --enable-dbus=no --without-libnl
  - make
  - make install
  - cd ..
  - rm -rf libpcap
  - git clone --branch dev https://github.com/ntop/nDPI.git
  - cd nDPI
  - ./autogen.sh
  - ./configure
  - make
  - make install
  - cd ..
  - rm -rf nDPI
  - pip install wheel twine setuptools codecov
  - pip install -r requirements.txt
  - python setup.py bdist_wheel
  - ls dist/

---
kind: pipeline
name: py37-on-arm32

platform:
  arch: arm

steps:
- name: build
  image: python:3.7
  commands:
  - apt-get update
  - apt-get -y install autogen autoconf automake libtool pkg-config libjson-c-dev gettext libusb-1.0-0-dev
  - apt-get -y install libdbus-glib-1-dev libbluetooth-dev libnl-genl-3-dev flex bison libpcap-dev
  - git clone --branch libgpg-error-1.39 https://github.com/gpg/libgpg-error
  - cd libgpg-error
  - ./autogen.sh
  - ./configure -enable-maintainer-mode --enable-static --enable-shared --with-pic --disable-doc --disable-nls
  - make
  - make install
  - cd ..
  - rm -rf libgpg-error
  - git clone --branch libgcrypt-1.8.6 https://github.com/gpg/libgcrypt
  - cd libgcrypt
  - ./autogen.sh
  - ./configure -enable-maintainer-mode --enable-static --enable-shared --with-pic --disable-doc
  - make
  - make install
  - cd ..
  - rm -rf libgcrypt
  - git clone --branch fanout https://github.com/tsnoam/libpcap
  - cd libpcap
  - ./configure --enable-ipv6 --disable-universal --enable-dbus=no --without-libnl
  - make
  - make install
  - cd ..
  - rm -rf libpcap
  - git clone --branch dev https://github.com/ntop/nDPI.git
  - cd nDPI
  - ./autogen.sh
  - ./configure
  - make
  - make install
  - cd ..
  - rm -rf nDPI
  - pip install wheel twine setuptools codecov
  - pip install -r requirements.txt
  - python setup.py bdist_wheel
  - ls dist/

---
kind: pipeline
name: py38-on-arm32

platform:
  arch: arm

steps:
- name: build
  image: python:3.8
  commands:
  - apt-get update
  - apt-get -y install autogen autoconf automake libtool pkg-config libjson-c-dev gettext libusb-1.0-0-dev
  - apt-get -y install libdbus-glib-1-dev libbluetooth-dev libnl-genl-3-dev flex bison libpcap-dev
  - git clone --branch libgpg-error-1.39 https://github.com/gpg/libgpg-error
  - cd libgpg-error
  - ./autogen.sh
  - ./configure -enable-maintainer-mode --enable-static --enable-shared --with-pic --disable-doc --disable-nls
  - make
  - make install
  - cd ..
  - rm -rf libgpg-error
  - git clone --branch libgcrypt-1.8.6 https://github.com/gpg/libgcrypt
  - cd libgcrypt
  - ./autogen.sh
  - ./configure -enable-maintainer-mode --enable-static --enable-shared --with-pic --disable-doc
  - make
  - make install
  - cd ..
  - rm -rf libgcrypt
  - git clone --branch fanout https://github.com/tsnoam/libpcap
  - cd libpcap
  - ./configure --enable-ipv6 --disable-universal --enable-dbus=no --without-libnl
  - make
  - make install
  - cd ..
  - rm -rf libpcap
  - git clone --branch dev https://github.com/ntop/nDPI.git
  - cd nDPI
  - ./autogen.sh
  - ./configure
  - make
  - make install
  - cd ..
  - rm -rf nDPI
  - pip install wheel twine setuptools codecov
  - pip install -r requirements.txt
  - python setup.py bdist_wheel
  - ls dist/

---
kind: pipeline
name: py39-on-arm32

platform:
  arch: arm

steps:
- name: build
  image: python:3.9
  commands:
  - apt-get update
  - apt-get -y install autogen autoconf automake libtool pkg-config libjson-c-dev gettext libusb-1.0-0-dev
  - apt-get -y install libdbus-glib-1-dev libbluetooth-dev libnl-genl-3-dev flex bison libpcap-dev
  - git clone --branch libgpg-error-1.39 https://github.com/gpg/libgpg-error
  - cd libgpg-error
  - ./autogen.sh
  - ./configure -enable-maintainer-mode --enable-static --enable-shared --with-pic --disable-doc --disable-nls
  - make
  - make install
  - cd ..
  - rm -rf libgpg-error
  - git clone --branch libgcrypt-1.8.6 https://github.com/gpg/libgcrypt
  - cd libgcrypt
  - ./autogen.sh
  - ./configure -enable-maintainer-mode --enable-static --enable-shared --with-pic --disable-doc
  - make
  - make install
  - cd ..
  - rm -rf libgcrypt
  - git clone --branch fanout https://github.com/tsnoam/libpcap
  - cd libpcap
  - ./configure --enable-ipv6 --disable-universal --enable-dbus=no --without-libnl
  - make
  - make install
  - cd ..
  - rm -rf libpcap
  - git clone --branch dev https://github.com/ntop/nDPI.git
  - cd nDPI
  - ./autogen.sh
  - ./configure
  - make
  - make install
  - cd ..
  - rm -rf nDPI
  - pip install wheel twine setuptools codecov
  - pip install -r requirements.txt
  - python setup.py bdist_wheel
  - ls dist/
