matrix:
  include:
    - os: linux
      arch: arm64
      language: python
      python: '3.6'
      env: PYTHON=/home/travis/virtualenv/python3.6.9/bin
      cache:
        directories:
          - $HOME/.pip-cache/
          - /home/travis/virtualenv/python3.6.9/lib/python3.6/site-packages
      addons:
        apt:
          packages:
            - autogen
            - autoconf
            - automake
            - libtool
            - pkg-config
            - libjson-c-dev
            - gettext
            - libusb-1.0-0-dev
            - libdbus-glib-1-dev
            - libbluetooth-dev
            - libnl-genl-3-dev
            - flex
            - bison

    - os: linux
      arch: arm64
      language: python
      python: '3.7'
      env: PYTHON=/home/travis/virtualenv/python3.7.5/bin
      cache:
        directories:
          - $HOME/.pip-cache/
          - /home/travis/virtualenv/python3.7.5/lib/python3.7/site-packages
      addons:
        apt:
          packages:
            - autogen
            - autoconf
            - automake
            - libtool
            - pkg-config
            - libjson-c-dev
            - gettext
            - libusb-1.0-0-dev
            - libdbus-glib-1-dev
            - libbluetooth-dev
            - libnl-genl-3-dev
            - flex
            - bison

    - os: linux
      arch: arm64
      language: python
      python: '3.8'
      env: PYTHON=/home/travis/virtualenv/python3.8.0/bin
      cache:
        directories:
          - $HOME/.pip-cache/
          - /home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages
      addons:
        apt:
          packages:
            - autogen
            - autoconf
            - automake
            - libtool
            - pkg-config
            - libjson-c-dev
            - gettext
            - libusb-1.0-0-dev
            - libdbus-glib-1-dev
            - libbluetooth-dev
            - libnl-genl-3-dev
            - flex
            - bison

install:
  - git clone --branch libgpg-error-1.39 https://github.com/gpg/libgpg-error
  - cd libgpg-error
  - ./autogen.sh
  - ./configure -enable-maintainer-mode --enable-static --enable-shared --with-pic --disable-doc --disable-nls
  - make
  - sudo make install
  - cd ..
  - rm -rf libgpg-error
  - git clone --branch libgcrypt-1.8.6 https://github.com/gpg/libgcrypt
  - cd libgcrypt
  - ./autogen.sh
  - ./configure -enable-maintainer-mode --enable-static --enable-shared --with-pic --disable-doc
  - make
  - sudo make install
  - cd ..
  - rm -rf libgcrypt
  - git clone --branch fanout https://github.com/tsnoam/libpcap
  - cd libpcap
  - ./configure --enable-ipv6 --disable-universal --enable-dbus=no --without-libnl
  - make
  - sudo make install
  - cd ..
  - rm -rf libpcap
  - git clone --branch dev https://github.com/ntop/nDPI.git
  - cd nDPI
  - ./autogen.sh
  - ./configure
  - make
  - sudo make install
  - cd ..
  - rm -rf nDPI
  - cd tests/
  - chmod a+x build_results.sh
  - ./build_results.sh
  - cd ..
  - python3 -m pip install --upgrade pip
  - python3 -m pip install --upgrade setuptools wheel twine codecov
  - python3 -m pip install -r requirements.txt
  - python3 setup.py bdist_wheel
  - ls dist/

script:
  - travis_wait python3 -m coverage run tests.py
  - python3 -m coverage combine

after_success:
  - python3 -m codecov
  - |
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ ! -z "$TRAVIS_TAG" ]; then
      python3 -m twine upload --skip-existing dist/*.whl
    fi